### PR TITLE
Explicitly list setup steps

### PR DESCRIPTION
**Pull request by aaroncrespo**
I was checking out this project during investigations into integrating a Native Component into Legacy Native App Via React Native (stretch goal of using Rome to bridge this to a Carthage managed project). 

However I was having some problems building/fetching everything from a fresh clone I added some missing steps, and fixed an error during `pod install`. I followed cocoapods suggestion for the error LMK how this patch works for you or if you would suggest another project to base this research off of.

### CODE REVIEW

**Comment by orta** [comment]
yes, good point I need to go through the tutorial again and update this repo incase there's any discrepancies

Thanks!

**Comment by aaroncrespo** [comment]
@orta while I have your attention and maybe I still haven't run across the right; maybe this repo isn't there yet but I have a question: 

Using this projects Example app project is it wrong to expect to be able to modify JS in /src and have the changes appear in the simulator on reload? Is it that some setup is missing to compile App.js into the GitDawg Bundle. When I try `yarn start`, `react-native start` or `npm start`, make changes and save I dont see any console output from the files being watched, and maybe relatedly RN 403's when requesting the updated JS (the 403 is visible in the bundler console)

```
::1 - - [09/Apr/2018:18:12:28 +0000] "GET /DerviedDataGitDawg_Example.app/GitDawg.js HTTP/1.1" 404 333 "http://localhost:8081/debugger-ui/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
```

This is all from a fresh clone and I haven't ever used react native before so my environment might not be 100% setup.

I see JS mentioning some issues with annotation but tbqh I dont think I'd know how to bridge Flow -> JS -> RN bundler.

**Comment by orta** [comment]
@aaroncrespo yes - it does not include these changes: https://github.com/artsy/artsy.github.io/blob/e8a4e3b8c2bf6a23cb91eaec5004995dc5afe131/_posts/2018-03-19-making-a-components-pod.markdown#what-now

See "What now?"

**Comment by aaroncrespo** [comment]
Thanks that helps a lot. I also didn't know about the command to build the bundle into Pod/Assets.

**Comment by orta** [comment]
You're welcome - Ash Furrow mentioned  an issue with integrating into GitHawk around the yoga import - I've not got that far on my second run through, so if you hit something like that later - it's the biggest known issue with the tutorial so far

**Pull request merged**
